# /**
#  * @author Abhijeet Padwal
#  * @email padwalab@gmail.com
#  * @create date 2020-11-17 03:11:50
#  * @modify date 2020-11-17 03:11:50
#  * @desc [description]
#  */
version: "3.3"
services:
  zookeeper_svc:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    # ports:
    #   - "2181:2181"
    networks:
      - splitwise_net
  kafka:
    image: kafka-docker_kafka
    expose:
      - "9092"
    # ports:
    #   - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_svc:2181
    depends_on:
      - zookeeper_svc
    networks:
      - splitwise_net
  splitwise_mongo:
    container_name: splitwise_mongo
    image: mongo:latest
    expose:
      - "27017"
    networks:
      - splitwise_net
    logging:
      driver: none
  splitwise_backend:
    container_name: splitwise_backend
    build:
      context: .
    volumes:
      - ./:/usr/src/spltws-backend
    command: npm run watch:dev
    ports:
      - "8000:8000"
    depends_on:
      - splitwise_mongo
      - kafka
    networks:
      - splitwise_net
networks:
  splitwise_net:
    driver: bridge
