# /**
#  * @author Abhijeet Padwal
#  * @email padwalab@gmail.com
#  * @create date 2020-11-17 03:11:50
#  * @modify date 2020-11-17 03:11:50
#  * @desc [description]
#  */
version: "3.3"
services:
  # splitwise-db:
  #   container_name: pg-db
  #   image: postgres:12
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=docker
  #     - POSTGRES_DB=test
  #     - DATABASE_HOST=splitwise-db

  #   # volumes:
  #   #   - ./config/init_pg.sql:/docker-entrypoint-initdb.d/init_pg.sql
  #   expose:
  #     - "5432"
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - splitwise_net
  #   logging:
  #     driver: none
  splitwise_mongo:
    container_name: splitwise_mongo
    image: mongo:latest
    expose:
      - "27017"
    # ports:
    #   - "27017:27017"
    networks:
      - splitwise_net
  splitwise_backend:
    container_name: splitwise_backend
    build:
      context: .
    volumes:
      - ./:/usr/src/splitwise-backend
    command: npm run start:dev
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - splitwise_mongo
    networks:
      - splitwise_net
  # splitwise_frontend:
  #   container_name: splitwise_frontend
  #   build:
  #     context: ./splitwise-frontend
  #     # dockerfile: ./splitwise-backend/Dockerfile
  #   volumes:
  #     - ./splitwise-frontend:/usr/src/splitwise-frontend
  #   expose:
  #     - "3000"
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - splitwise_backend
  #   networks:
  #     - splitwise_net

networks:
  splitwise_net:
    driver: bridge
