# /**
#  * @author Abhijeet Padwal
#  * @email padwalab@gmail.com
#  * @create date 2020-11-17 03:11:50
#  * @modify date 2020-11-17 03:11:50
#  * @desc [description]
#  */
version: "3.3"
services:
  splitwise_mongo:
    container_name: splitwise_mongo
    image: mongo:latest
    expose:
      - "27017"
    networks:
      - splitwise_net
  splitwise_backend:
    container_name: splitwise_backend
    build:
      context: .
    volumes:
      - ./:/usr/src/splitwise-backend
    command: npm run start:dev
    expose:
      - "9000"
    ports:
      - "9000:9000"
    depends_on:
      - splitwise_mongo
    networks:
      - splitwise_net
networks:
  splitwise_net:
    driver: bridge
